name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t devsecops-flask-app .

      - name: Run tests
        run: docker run devsecops-flask-app python -m pytest

      - name: Run SonarCloud Analysis
        env:
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="https://sonarcloud.io" \
            -e SONAR_TOKEN=$SONARCLOUD_TOKEN \
            -e SONAR_PROJECT_KEY=Sirelfer_devsecops-flask-app \
            -e SONAR_ORGANIZATION=sirelfer \
            -v "$(pwd):/usr/src" \
            sonarsource/sonar-scanner-cli